airbnb:
  outputs:
    dev:
      dataset: airbnb
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /home/danh/workspace/self-study/eu-airbnb/cred/dtc-airbnb-33c84c172b76.json
      location: US
      method: service-account
      priority: interactive
      project: dtc-airbnb
      threads: 1
      type: bigquery
  target: dev
